### ISSUE TITLE
Couple good sounds for the pack

### ISSUE THREAD

**Issue by Thaz0n** [Kuoxsr/fhb-villager-sounds#6]
https://clips.twitch.tv/AcceptableCourteousRabbitBatChest-ak0521ORBQ_XYBIB

Also https://clips.twitch.tv/AlertCallousPrariedogBrainSlug-6u2RYR80SVboAm2P

Thanks for the work!

**Comment by Kuoxsr** [comment]
Thanks, again, @Thaz0n!  I got 5 sounds out of these clips.  These sounds will appear in version 3.0, which will hopefully be released before the end of February (if I can stay focused and stop procrastinating.)  If you'd like to try it immediately, you could clone my repo to your hard drive and build the pack yourself.  I should probably write better instructions for how to do that, but that's for another day.

Please feel free to start new issues for more clips in the future.  This worked as well as I thought it would.  Thank you so much!
